<?php
/**
 * @var array $_CONFIG
 */
# PLEASE READ ALL THE COMMENTS TO HELP YOU LEARN HOW TO CONFIGURE.
# NO HELP WILL BE PROVIDED IF THE QUESTION CAN BE ANSWERED IN THIS CONFIG FILE.
//
// >> DATABASE AND API KEYS RELATED STUFF, CONFIDENTIAL
//
$_CONFIG["db_host"] = "";
$_CONFIG["db_name"] = "";
$_CONFIG["db_username"] = "";
$_CONFIG["db_password"] = "";
